name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Preparar Buildozer
        run: |
          buildozer --version

      - name: Construir APK
        run: |
          buildozer -v android debug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: thermoplantio-apk
          path: bin/*.apk
