name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-virtualenv \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            gettext \
            autopoint

      - name: Instalar Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade buildozer cython

      - name: Preparar herramientas de compilación
        run: |
          autoreconf --version
          autoconf --version
          automake --version
          libtool --version

      - name: Configurar Buildozer
        run: |
          buildozer --version

      - name: Construir APK
        run: |
          buildozer -v android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: thermo-plant-io-apk
          path: bin/*.apk
          if-no-files-found: error
